import React from 'react';
import { ArrowRight, BarChart2, ShieldCheck, Zap } from 'lucide-react';

interface HeroProps {
  onStart: () => void;
}

const Hero: React.FC<HeroProps> = ({ onStart }) => {
  return (
    <div className="relative min-h-screen flex items-center justify-center overflow-hidden">
      {/* Background Decor */}
      <div className="absolute top-0 left-0 w-full h-full z-0 pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] bg-blue-600/20 rounded-full blur-[100px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] bg-purple-600/20 rounded-full blur-[100px]" />
      </div>

      <div className="relative z-10 container mx-auto px-6 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-sm font-medium mb-8 animate-fade-in-up">
          <Zap size={16} />
          <span>AI-Powered Business Intelligence</span>
        </div>
        
        <h1 className="text-5xl md:text-7xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white via-blue-100 to-blue-200 mb-6 leading-tight tracking-tight">
          Unlock Your Business's <br/> Hidden Potential
        </h1>
        
        <p className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed">
          GrowthMind analyzes your unique business footprint to generate a bespoke roadmap, predicting revenue opportunities and identifying critical bottlenecks in seconds.
        </p>

        <button 
          onClick={onStart}
          className="group relative inline-flex items-center justify-center px-8 py-4 text-lg font-semibold text-white transition-all duration-200 bg-blue-600 rounded-full hover:bg-blue-500 hover:scale-105 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600 focus:ring-offset-slate-900 shadow-[0_0_20px_rgba(37,99,235,0.3)]"
        >
          <span>Start Free Audit</span>
          <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
        </button>

        <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8 text-left max-w-4xl mx-auto">
          <div className="glass-panel p-6 rounded-xl hover:bg-slate-800/50 transition-colors">
            <div className="w-12 h-12 bg-blue-500/20 rounded-lg flex items-center justify-center text-blue-400 mb-4">
              <BarChart2 size={24} />
            </div>
            <h3 className="text-lg font-semibold text-white mb-2">Deep Data Analysis</h3>
            <p className="text-slate-400 text-sm">We process your inputs against thousands of industry benchmarks to find gaps.</p>
          </div>
          <div className="glass-panel p-6 rounded-xl hover:bg-slate-800/50 transition-colors">
            <div className="w-12 h-12 bg-purple-500/20 rounded-lg flex items-center justify-center text-purple-400 mb-4">
              <ShieldCheck size={24} />
            </div>
            <h3 className="text-lg font-semibold text-white mb-2">Strategic Clarity</h3>
            <p className="text-slate-400 text-sm">Receive a clear, actionable SWOT analysis tailored to your specific market position.</p>
          </div>
          <div className="glass-panel p-6 rounded-xl hover:bg-slate-800/50 transition-colors">
            <div className="w-12 h-12 bg-emerald-500/20 rounded-lg flex items-center justify-center text-emerald-400 mb-4">
              <Zap size={24} />
            </div>
            <h3 className="text-lg font-semibold text-white mb-2">Instant Roadmap</h3>
            <p className="text-slate-400 text-sm">Get a step-by-step execution plan generated by our advanced Gemini models.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Hero;
